version: '3'
services:

 web1:
  build: .
  ports:
    - "8080:8081"
    - "0.0.0.0:5701:5701"
  links:
    - db
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes
    - VALOR_HAZELCAST_IP=192.168.0.31

 web2:
  build: .
  ports:
    - "8081:8081"
    - "0.0.0.0:5702:5701"
  links:
    - db
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes
    - VALOR_HAZELCAST_IP=192.168.0.31

 db:
  image: mysql:5.7
  ports:
     - '3306:3306'
  restart: always
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_USER: 'easynotes'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
 

 
  
