version: '3'
services:

 web1:
  build: .
  ports:
    - "8080:8081"
#links to de BBDD
  links:
    - db
#ADD VOLUME FROM FILES SYSTEM
  volumes:
    - ./Files:/app/Files

  
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes

 web2:
  build: .
  ports:
    - "8081:8081"
  links:
    - db
  volumes:
    - ./Files:/app/Files
  
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes

 db:
  image: mysql:5.7
  ports:
     - '3306:3306'
  restart: always
#ADD VOLUME FOR SQL PERSISTENCY
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_USER: 'easynotes'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
 

 
  
