version: '3'
services:

 haproxy:
   build: ./ServicioHaproxy
   ports:
     - '80:80'
   environment:
     - WEB_SERVICE_IP1=web1
     - WEB_SERVICE_IP2=web2
     - WEB_SERVICE_PORT1=8081
     - WEB_SERVICE_PORT2=8081


 web1:
  build: ./ServicioWeb
#links to de BBDD

#ADD VOLUME FROM FILES SYSTEM
  volumes:
    - ./Files:/app/Files
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes
    - VALOR_MAIL_IP=mail
 web2:
  build: ./ServicioWeb
  volumes:
    - ./Files:/app/Files
  
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/easynotes
    - VALOR_MAIL_IP=mail
 mail:
   build: ./ServicioMail

 db:
  image: mysql:5.7
  ports:
     - '3306:3306'
  restart: always
#ADD VOLUME FOR SQL PERSISTENCY
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_USER: 'easynotes'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
 

 
  
