version: '3'
services:
 mysql-master:
  build:
    context: ./
    dockerfile: master/DockerFile
  container_name: "mysql-master"
  ports:
     - 3307:3306
  restart: always
#ADD VOLUME FOR SQL PERSISTENCY
  volumes:
    - ./master/my.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    - ./master/data:/var/lib/mysql
  environment:
    MYSQL_USER: 'easynotes'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
  hostname: mysql-master
  networks:
    - overlay

 mysql-slave:
  build:
    context: ./
    dockerfile: slave/DockerFile
  container_name: "mysql-slave"
  ports:
     - 3308:3306
  restart: always
  depends_on:
    - mysql-master
  volumes:
    - ./slave/my.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    - ./slave/data:/var/lib/mysql
  environment:
    MYSQL_USER: 'easynotes_replic'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
  hostname: mysql-slave
  networks:
    - overlay

networks:
  overlay:
