version: '3'
services:


 db:
  image: mysql:5.7
  ports:
     - '3306:3306'
  restart: always
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_USER: 'easynotes'
    MYSQL_PASSWORD: '1234'
    MYSQL_ROOT_PASSWORD: '1234'
    MYSQL_DATABASE: 'easynotes'
    MYSQL_ROOT_HOST: '%'
 

 
  
