STOP SLAVES;

CHANGE MASTER TO
    MASTER_HOST='mysql-master',
    MASTER_USER='easynotes',
    MASTER_PASSWORD='1234',
    MASTER_PORT=3306,
    MASTER_USE_GTID=slave_pos,
    MASTER_CONNECT_RETRY=10;

START SLAVES;
